### ISSUE TITLE
TimeUnit doesn't really need to be a type class

### ISSUE THREAD

**Issue by colonelpanic8** [acw/time-units#3]
It seems like it would be much easier (and allow type signatures to be less complicated) if it were an ADT such as
``` haskell
data TimeUnit
  = Microsecond Integer
  | Millisecond Integer
  | Second Integer
deriving (...)

toMicroseconds :: TimeUnit -> Integer
toMicroseconds Microsecond val = val
toMicroseconds Second val = val * (10 ^ 6)
```

What does the typeclass even buy you here, other than the ability to add new increments of time, I suppose. If you really wanted that ability, you could keep the type class but keep the implementation mostly in 1 data type which would still be better IMO.

**Comment by acw** [comment]
The ability to add new increments was pretty much my major goal, since I doubted I'd think of all the important ones.
